site_name: Django UrlConf Checks
site_url: https://AliSayyah.github.io/django-urlconfchecks
repo_url: https://github.com/AliSayyah/django-urlconfchecks
repo_name: AliSayyah/django-urlconfchecks
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tracking
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - django-urlconfchecks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AliSayyah/django-urlconfchecks
      name: Github
    - icon: material/email
      link: "mailto:ali.sayyah2@gmail.com"
