name: Changelog

on:
  pull_request:
    types: [closed]
    
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          output: release-notes.md
          future_release: future_release

      - name: Commit files
        env:
          CI_USER: ${{ secrets.USER }}
          CI_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"
          git add release-notes.md && git commit -m 'Updated release-notes.md' && echo "push=true" >> $GITHUB_ENV || echo "No changes to release-notes.md"

      - name: Push changes
        if: env.push == 'true'
        env:
          CI_USER: ${{ secrets.USER }}
          CI_TOKEN: ${{ secrets.PERSONAL_TOKEN}}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:main
